// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLTqnHRkoaf3GclcZ-gTmHIJbJQwldkaM',
    appId: '1:394716292771:web:854cf1438be7825c614116',
    messagingSenderId: '394716292771',
    projectId: 'chat-app-a2f8c',
    authDomain: 'chat-app-a2f8c.firebaseapp.com',
    storageBucket: 'chat-app-a2f8c.appspot.com',
    measurementId: 'G-NE21X4GBN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHeT4krDarwQZl8iG0Ula0acK9uvxCvkQ',
    appId: '1:394716292771:android:315588a773ab50c5614116',
    messagingSenderId: '394716292771',
    projectId: 'chat-app-a2f8c',
    storageBucket: 'chat-app-a2f8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHfGWwWZ3T6Rk1GalrzhqR27GJEjD6JY',
    appId: '1:394716292771:ios:180fe96eb9bbd387614116',
    messagingSenderId: '394716292771',
    projectId: 'chat-app-a2f8c',
    storageBucket: 'chat-app-a2f8c.appspot.com',
    iosClientId: '394716292771-8jl98icj1t31r62ilpme08ok048j86j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASHfGWwWZ3T6Rk1GalrzhqR27GJEjD6JY',
    appId: '1:394716292771:ios:180fe96eb9bbd387614116',
    messagingSenderId: '394716292771',
    projectId: 'chat-app-a2f8c',
    storageBucket: 'chat-app-a2f8c.appspot.com',
    iosClientId: '394716292771-8jl98icj1t31r62ilpme08ok048j86j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
